# Copyright 2025 Clidey, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: whodb
version: git
summary: Lightweight database management tool
description: |
  WhoDB is a lightweight, next-generation database management tool for
  developers and database administrators. It provides an intuitive interface
  for managing multiple database types including PostgreSQL, MySQL, SQLite,
  MongoDB, Redis, and more.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  whodb:
    command: bin/whodb
    desktop: share/applications/whodb.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - network
      - network-bind
      - opengl

parts:
  # Build Node/frontend dependencies first
  frontend:
    plugin: nil
    source: frontend
    source-type: local
    build-packages:
      - curl
      - ca-certificates
    override-build: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      apt-get install -y nodejs

      # Install pnpm
      npm install -g pnpm

      # Build frontend
      pnpm install
      pnpm run build:ce

      # Stage the build output for the next part
      mkdir -p $SNAPCRAFT_PART_INSTALL/frontend-dist
      cp -r build/* $SNAPCRAFT_PART_INSTALL/frontend-dist/

  whodb:
    after: [ frontend ]
    plugin: nil
    source: .
    source-type: local
    build-environment:
      - CGO_ENABLED: "1"
      - PATH: "/snap/go/current/bin:$PATH"
      - GOPATH: "$HOME/go"
      - GOWORK: "$PWD/go.work.desktop-ce"
    build-snaps:
      - go/latest/stable
    build-packages:
      - gcc
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libwebkit2gtk-4.1-dev
      - pkg-config
      - upx-ucl
    stage-packages:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37
      - libwebkit2gtk-4.1-0
    override-build: |
      if [ -n "$SNAPCRAFT_PROJECT_VERSION" ]; then
        snapcraftctl set-version "$SNAPCRAFT_PROJECT_VERSION"
      fi

      # Copy frontend build from previous part
      mkdir -p desktop-ce/frontend/dist
      cp -r $SNAPCRAFT_STAGE/frontend-dist/* desktop-ce/frontend/dist/

      # Install Wails
      go install github.com/wailsapp/wails/v2/cmd/wails@latest
      export PATH=$PATH:$HOME/go/bin

      # Change to desktop-ce directory (just like other builds do)
      cd desktop-ce

      # Build the desktop app - from desktop-ce with proper parent structure
      GOWORK=$PWD/../go.work.desktop-ce wails build -clean -tags desktop,production,!ee -ldflags="-s -w" -o whodb

      # Install the binary
      install -D -m755 build/bin/whodb $SNAPCRAFT_PART_INSTALL/bin/whodb

  desktop-file:
    plugin: dump
    source: linux
    organize:
      whodb.desktop: share/applications/whodb.desktop
      icon.png: share/icons/hicolor/256x256/apps/whodb.png
