# Copyright 2025 Clidey, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: whodb
version: git
summary: Lightweight database management tool
description: |
  WhoDB is a lightweight, next-generation database management tool for
  developers and database administrators. It provides an intuitive interface
  for managing multiple database types including PostgreSQL, MySQL, SQLite,
  MongoDB, Redis, and more.

base: core22
confinement: strict
grade: stable
title: WhoDB
license: Apache-2.0
contact: mailto:support@whodb.com
website: https://whodb.com
source-code: https://github.com/clidey/whodb
issues: https://github.com/clidey/whodb/issues
donation: https://github.com/sponsors/clidey
icon: linux/icon.png

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/lib/aarch64-linux-gnu/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/aarch64-linux-gnu/webkit2gtk-4.0
  /usr/lib/aarch64-linux-gnu/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/aarch64-linux-gnu/webkit2gtk-4.1

apps:
  whodb:
    command: bin/whodb
    desktop: share/applications/whodb.desktop
    environment:
      WEBKIT_DISABLE_COMPOSITING_MODE: "1"
      WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS: "1"
      GDK_BACKEND: "x11,wayland"
      GTK_USE_PORTAL: "0"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH"
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - network
      - network-bind
      - opengl
      - browser-support
      - audio-playback
      - unity7
      - home

parts:
  # Build Node/frontend dependencies first
  frontend:
    plugin: nil
    source: frontend
    source-type: local
    build-packages:
      - curl
      - ca-certificates
    override-build: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      apt-get install -y nodejs

      # Install pnpm
      npm install -g pnpm

      # Build frontend
      pnpm install
      pnpm run build:ce

      # Stage the build output for the next part
      mkdir -p $SNAPCRAFT_PART_INSTALL/frontend-dist
      cp -r build/* $SNAPCRAFT_PART_INSTALL/frontend-dist/

  versioner:
    plugin: nil

  whodb:
    after: [ frontend ]
    plugin: nil
    source: .
    source-type: local
    build-environment:
      - CGO_ENABLED: "1"
      - PATH: "/snap/go/current/bin:$PATH"
      - GOPATH: "$HOME/go"
      - GOWORK: "$PWD/go.work.desktop-ce"
    build-snaps:
      - go/latest/stable
    build-packages:
      - gcc
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libwebkit2gtk-4.1-dev
      - pkg-config
      - upx-ucl
    stage-packages:
      - libgtk-3-0
      - libwebkit2gtk-4.0-37
      - libwebkit2gtk-4.1-0
      - libcanberra-gtk3-module
      - libcanberra-gtk-module
      - libglu1-mesa
      - freeglut3
      - libgpm2
      - libslang2
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libgles2-mesa
      - libegl1-mesa
      - libjavascriptcoregtk-4.0-18
      - libjavascriptcoregtk-4.1-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-gl
      - libsoup-3.0-0
      - libsecret-1-0
      - libenchant-2-2
      - libhyphen0
      - libwoff1
      - libgstreamer-gl1.0-0
    prime:
      # Explicitly include WebKit subprocess executables
      - usr/lib/*/webkit2gtk-4.0/*
      - usr/lib/*/webkit2gtk-4.1/*
      # Exclude unnecessary libraries to reduce snap size
      - -usr/lib/*/caca/libgl_plugin.so.*
      - -usr/lib/*/libcaca++.so.*
      - -usr/lib/*/libcolordprivate.so.*
      - -usr/lib/*/libdconf.so.*
      - -usr/lib/*/libexslt.so.*
      - -usr/lib/*/libgstcheck-1.0.so.*
      - -usr/lib/*/libgstcontroller-1.0.so.*
      - -usr/lib/*/libicuio.so.*
      - -usr/lib/*/libicutest.so.*
      - -usr/lib/*/libjacknet.so.*
      - -usr/lib/*/libjackserver.so.*
      - -usr/lib/*/liborc-test-0.4.so.*
      - -usr/lib/*/libpulse-simple.so.*
      - -usr/lib/*/libunwind-*.so.*
      - -usr/lib/*/libwoff2enc.so.*
      - -usr/lib/*/libEGL_mesa.so.*
      - -usr/lib/*/libGLESv2.so.*
      - -usr/lib/*/libGLX_mesa.so.*
    override-build: |
      # Copy frontend build from previous part
      mkdir -p desktop-ce/frontend/dist
      cp -r $SNAPCRAFT_STAGE/frontend-dist/* desktop-ce/frontend/dist/

      # Install Wails
      go install github.com/wailsapp/wails/v2/cmd/wails@latest
      export PATH=$PATH:$HOME/go/bin

      # Change to desktop-ce directory (just like other builds do)
      cd desktop-ce

      # Build the desktop app - from desktop-ce with proper parent structure
      GOWORK=$PWD/../go.work.desktop-ce wails build -clean -tags desktop,production,!ee -ldflags="-s -w" -o whodb

      # Install the binary
      install -D -m755 build/bin/whodb $SNAPCRAFT_PART_INSTALL/bin/whodb

  desktop-file:
    plugin: dump
    source: linux
    override-build: |
      install -D whodb.desktop $CRAFT_PART_INSTALL/share/applications/whodb.desktop
      install -D icon.png $CRAFT_PART_INSTALL/share/icons/hicolor/256x256/apps/whodb.png
      install -D icon.png $CRAFT_PART_INSTALL/meta/gui/whodb.png
    prime:
      - share/applications/whodb.desktop
      - share/icons/hicolor/256x256/apps/whodb.png
      - meta/gui/whodb.png
