# Copyright 2025 Clidey, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: whodb
version: git
summary: Lightweight database management tool
description: |
  WhoDB is a lightweight, next-generation database management tool for
  developers and database administrators. It provides an intuitive interface
  for managing multiple database types including PostgreSQL, MySQL, SQLite,
  MongoDB, Redis, and more.

base: core22
confinement: classic
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  whodb:
    command: bin/whodb
    desktop: share/applications/whodb.desktop

parts:
  # Build Node/frontend dependencies first
  frontend:
    plugin: nil
    source: ../frontend
    source-type: local
    build-packages:
      - curl
      - ca-certificates
    override-build: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      apt-get install -y nodejs

      # Install pnpm
      npm install -g pnpm

      # Build frontend
      pnpm install
      pnpm run build:ce

      # Stage the build output for the next part
      mkdir -p $SNAPCRAFT_PART_INSTALL/frontend-dist
      cp -r build/* $SNAPCRAFT_PART_INSTALL/frontend-dist/

  whodb:
    after: [ frontend ]
    plugin: go
    source: .
    source-type: local
    build-environment:
      - CGO_ENABLED: "1"
      - GOWORK: "../go.work.desktop-ce"
    build-packages:
      - gcc
      - libgtk-3-dev
      - libwebkit2gtk-4.1-dev
      - upx-ucl
    stage-packages:
      - libgtk-3-0
      - libwebkit2gtk-4.1-0
    override-build: |
      # Copy frontend build from previous part
      mkdir -p frontend/dist
      cp -r $SNAPCRAFT_STAGE/frontend-dist/* frontend/dist/

      # Install Wails
      go install github.com/wailsapp/wails/v2/cmd/wails@latest
      export PATH=$PATH:$(go env GOPATH)/bin

      # Build the desktop app
      wails build -clean -tags desktop,production,!ee -ldflags="-s -w" -o whodb

      # Install the binary
      install -D -m755 build/bin/whodb $SNAPCRAFT_PART_INSTALL/bin/whodb

  desktop-file:
    plugin: dump
    source: linux/
    organize:
      whodb.desktop: share/applications/whodb.desktop
      icon.png: share/icons/hicolor/256x256/apps/whodb.png
