name: Build Snap Packages

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string
      upload-artifacts:
        description: 'Whether to upload artifacts'
        required: false
        type: boolean
        default: true
    secrets:
      SNAPCRAFT_STORE_CREDENTIALS:
        required: false

jobs:
  build-snap:
    name: Build Snap (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    env:
      SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "1"
      SNAPCRAFT_PROJECT_VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Install build dependencies
        run: |
          # Update package lists
          sudo apt-get update

          # Install essential build tools
          sudo apt-get install -y \
            build-essential \
            curl \
            git \
            pkg-config

          echo "Build dependencies installed"

      - name: Setup Snapcraft
        run: |
          sudo snap install snapcraft --classic
          echo "Snapcraft version:"
          snapcraft --version

      - name: Build Snap package
        id: build_snap
        run: |
          echo "Building snap with version: ${{ inputs.version }}"

          # Write version to a file that snapcraft can read
          echo "${{ inputs.version }}" > .snap_version

          # Run snapcraft with destructive mode
          sudo snapcraft --destructive-mode --verbosity=debug

          echo "✅ Snap built successfully"
          echo "build_method=destructive" >> $GITHUB_OUTPUT

      - name: Verify Snap
        run: |
          SNAP_FILE=$(ls *.snap 2>/dev/null | head -1)
          if [ -z "$SNAP_FILE" ]; then
            echo "❌ No snap file found after build"
            exit 1
          fi

          echo "✅ Built snap: $SNAP_FILE"
          echo "File size: $(du -h "$SNAP_FILE" | cut -f1)"
          echo "Expected version: ${{ inputs.version }}"

          # Verify filename contains version (be flexible about format)
          SNAP_BASENAME=$(basename "$SNAP_FILE")
          VERSION="${{ inputs.version }}"
          VERSION_NO_V="${VERSION#v}"  # Remove leading 'v' if present

          if [[ "$SNAP_BASENAME" == *"_${VERSION}_"* ]] || [[ "$SNAP_BASENAME" == *"_${VERSION_NO_V}_"* ]]; then
            echo "✅ Snap filename contains correct version"
          else
            echo "⚠️ Warning: Snap filename $SNAP_BASENAME may not contain expected version ${VERSION}"
            echo "This is not critical, continuing..."
          fi

      - name: Upload Snap artifact
        if: inputs.upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snap-package-${{ matrix.arch }}
          path: "*.snap"
          retention-days: 1